services:
  db:
    image: postgres:15
    container_name: delivery_postgres
    restart: always
    environment:
      POSTGRES_DB: delivery_data
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: delivery_pass
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U delivery_user -d delivery_data"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    container_name: delivery_api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./api:/app
      - ./api/logs:/app/logs  # 日志目录
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket，用于创建临时容器
      - .:/workspace  # 挂载项目根目录，用于构建其他服务的镜像
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000


  scheduler:
    build: ./scheduler
    container_name: delivery_scheduler
    depends_on:
      - api
    volumes:
      - ./api/logs:/app/logs  # 日志目录共享
    restart: unless-stopped
volumes:
  pg_data: